language: node_js
node_js:
  - '0.10'
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - gem install sass
  - gem install compass
before_script:
  - npm run preinstall
  - bower install --force
addons:
  code_climate:
    repo_token: 6072ec34cdd7eec6b29ffc071f1575f41c27fa39e2dbe54fdc4d329c7dd372f4
after_script:
  - cat coverage/phantomjs/lcov.info | codeclimate
