language: node_js
node_js:
  - '0.10'
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - gem install sass
  - gem install compass
before_script:
  - npm run preinstall
  - bower install --force
addons:
  code_climate:
    repo_token:
      secure: "NKG/TxSc7vk+956Nc6ZgCmHvF90FV58wyvInBaU9I3zWsjBfJVxGSsaMVh/b2qXnAudekuZaNACFXItPManvnSoy1vHI3KwjTcltXOe36L7CD1QsZROAS+oifpBRre+qv1AgPv+hiG8fSMbUmFtbzonI3yPbiF/4i/844cB39dU="
after_script:
  - cat coverage/phantomjs/lcov.info | codeclimate
